### ISSUE TITLE
last_seen not recognised for campaign or intrusion-set objects

### ISSUE THREAD

**Issue by JoeP-oss** [oasis-open/cti-stix-validator#116]
Using v1.1.2 from pip3, when validating a `campaign` object with a `last_seen` timestamp, causes the following warning: 

> {101} Custom property 'last_seen' should have a type that starts with 'x_' followed by a source unique identifier (like a domain name with dots replaced by hyphen), a hyphen and then the name.

[STIX™ Version 2.0. Part 2: STIX Objects](http://docs.oasis-open.org/cti/stix/v2.0/cs01/part2-stix-objects/stix-v2.0-cs01-part2-stix-objects.html#_Toc496714304) states this is a valid attribute for campaign objects; can this be added and validated as a timestamp.

**Comment by JoeP-oss** [comment]
Also affecting `intrusion-set` objects; interestingly it is correctly validating it as timestamp while saying it is a custom property.

**Error**

> intrusion-set--736bcbc4-48f8-46b3-ad0b-b9598135404b: last_seen: '2020-01-15:15:42.513Z' does not match the timestamp format YYYY-MM-DDTHH:mm:ss[.s+]Z

**Warning**

> intrusion-set--736bcbc4-48f8-46b3-ad0b-b9598135404b: {101} Custom property 'last_seen' should have a type that starts with 'x_' followed by a source unique identifier (like a domain name with dots replaced by hyphen), a hyphen and then the name.

**Comment by clenk** [comment]
Good find, thanks! We fixed this for STIX 2.1 but forgot to for 2.0. This fix will be included in the next release.
