### ISSUE TITLE
The validator should allow upper case letters in a MAC address

### ISSUE THREAD

**Issue by rpiazza** [oasis-open/cti-stix-validator#124]
This is the pattern used in the validator: "pattern": "^([0-9a-f]{2}[:]){5}([0-9a-f]{2})$",

Here is a link to some official IEEE documentation, which seems to indicate upper case is fine.

https://standards.ieee.org/content/dam/ieee-standards/standards/web/documents/tutorials/macgrp.pdf

**Comment by clenk** [comment]
The STIX 2.1 spec layers on additional restrictions in section 6.10.1 (emphasis mine):

> The MAC address value MUST be represented as a single colon-delimited, **lowercase** MAC-48 address, which MUST include leading zeros for each octet.

Also, this regex is from the schemas rather than the validator.

**Comment by rpiazza** [comment]
@clenk - that is completely arbitrary - I'll ask Bret about it.
