### ISSUE TITLE
Open Vocab changes for 2.1 WD07

### ISSUE THREAD

**Issue by clenk** [oasis-open/cti-stix-validator#136]
* i[dentity-class-ov](https://github.com/oasis-open/cti-stix-validator/blob/6865750dc05f99a2ceb96124ceaf231d282fa4df/stix2validator/v21/enums.py#L40) - changed unspecified to unknown
* [industry-sector-ov](https://github.com/oasis-open/cti-stix-validator/blob/6865750dc05f99a2ceb96124ceaf231d282fa4df/stix2validator/v21/enums.py#L80) - changed defence to defense, added chemical, commercial, government (emergency-services, government-local, government-national, government-public-services,  government-regional), infrastructure (dams, nuclear, water)
* [infrastructure-type-ov](https://github.com/oasis-open/cti-stix-validator/blob/6865750dc05f99a2ceb96124ceaf231d282fa4df/stix2validator/v21/enums.py#L109) - changed unspecified to unknown

**Comment by emmanvg** [comment]
Working on it...
