### ISSUE TITLE
Validator requires version property for observed-data

### ISSUE THREAD

**Issue by jmgnc** [oasis-open/cti-stix-validator#14]
For the attached file
[observ.txt](https://github.com/oasis-open/cti-stix-validator/files/740658/observ.txt)

It will pass even though the version property is present though it should not be (other objects do not require it).

If you do have the "required" version property present, it then warns about it being a custom property and should have a prefix of x_.

**Comment by gtback** [comment]
@clenk, @atweedmitre: can one of you look at this?

**Comment by clenk** [comment]
'version' is not a property mentioned in the current spec. It is not a common property, an observed-data property, nor a reserved property. Thus it is considered a custom property, and isn't required, but isn't prohibited either.

Please let me know if my reading of the spec is incorrect.

**Comment by jmgnc** [comment]
Sorry, my bug report was incomplete.  If you remove the version property, the stix validator says that it is a required property:
================================================================================
[-] Results for: observ.json
[X] STIX JSON: Invalid
   [!] Warning: observed-data--7d69c058-034b-4769-9e7f-f7b080abf80d: {301} The Network Traffic object '0' should contain both the 'src_port' and 'dst_port' properties.
  [X] observed-data--7d69c058-034b-4769-9e7f-f7b080abf80d: 'version' is a required property

So the validator is requiring you to add a custom property named version to pass.

**Comment by clenk** [comment]
Thank you for posting the output. This should have been fixed in https://github.com/oasis-open/cti-stix2-json-schemas/commit/e5b476617ed214b0a586eed5fe95fa10df6ad29f. Can you verify that you are using the latest version of the schemas?

**Comment by jmgnc** [comment]
ok, looks like it was an out of date validator.  I thought I had updated it, but clearly had not done it completely and/or correctly.

**Comment by gtback** [comment]
The validator uses the schemas as a submodule, so if you're working from the git repositories, maybe you updated the validator, but not the version of the schemas?
