### ISSUE TITLE
intrusion-set seems not to be viewed as a type?

### ISSUE THREAD

**Issue by denny-lclin** [oasis-open/cti-stix-validator#152]
package version: 2.0.1

I got a  bundle like: 

{
  "objects": [
    {
      "id": "intrusion-set--01f18402-1708-11e8-ac1c-1ffb3c4a7775",
      "type": "intrusion-set",
      "created": "2020-07-23T00:00:00.000Z",
      "modified": "2020-07-26T00:01:10.000Z",
      "name": "object name",
      "description": "blah blah",
      "aliases": [
        "abc"
      ],
      "labels": [],
      "created_by_ref": "identity--5cf66e53-b5f8-43e7-be9a-49880a3b4631"
    }
  ],
  "type": "bundle",
  "id": "bundle--7e1ccb76-66e3-4f42-9055-631a56d45e94",
  "spec_version": "2.0"
}

and the validate_file() output errors:
[X] report--3aaa35fb-1d80-4e35-a324-f001535b7e29: object_refs[44]: 'intrusion-set--01f18402-1708-11e8-ac1c-1ffb3c4a7775' does not match the id format ([object-type]--[UUID])
[X] intrusion-set--01f18402-1708-11e8-ac1c-1ffb3c4a7775: id: 'intrusion-set--01f18402-1708-11e8-ac1c-1ffb3c4a7775' does not match the id format ([object-type]--[UUID])

Do I miss something?

**Comment by clenk** [comment]
Hi @denny-lclin. The UUID portion of that ID seems to be a UUIDv**1**: 

```python
>>> import uuid
>>> x = uuid.UUID('01f18402-1708-11e8-ac1c-1ffb3c4a7775')
>>> x.version
1
```

STIX 2 requires UUIDv**4** for SDOs. Let us know if you have further questions! :)

**Comment by denny-lclin** [comment]
@clenk  Thanks for your prompt reply 👍
