### ISSUE TITLE
Latitude is Misspelled Causing Validator to Assume it's a "custom property"

### ISSUE THREAD

**Issue by cbush06** [oasis-open/cti-stix-validator#160]
https://github.com/oasis-open/cti-stix-validator/blob/2aefc8ca80bb94022e777dba185503825e46b05a/stix2validator/v21/enums.py#L657

**Comment by clenk** [comment]
Thank you for bringing this to our attention, @cbush06! This should be fixed in the latest version, v2.0.4.
