### ISSUE TITLE
Validation should fail when `*_bin` values aren't base64 encoded

### ISSUE THREAD

**Issue by rpatterson** [oasis-open/cti-stix-validator#17]
When the `cti-pattern-matcher` library tries to match a pattern that matches on a value such as `payload_bin` on observed data where `payload_bin` contains unencoded text, the library raises an exception because it can't decode it as base64.  However, that same observed data doesn't show up as a validation error when run through the validator.  So it seems like this is something that should be checked by the validator.

**Comment by gtback** [comment]
Thanks, @rpatterson!

`cti-stix-validator` defers to `cti-pattern-validator` to validate the patterns, so it would probably be best to fix this in the pattern validator. Both `cti-pattern-matcher` and `cti-pattern-validator` use the same ANTLR grammar, but it's possible the pattern matcher does more restrictive checks when actually matching the patterns than the validator does when validating it; if so, that should be fixed.

Do you have some example data that demonstrates this? 

cc: @clenk @chisholm

**Comment by chisholm** [comment]
I may misunderstand, but the validator merely validates _patterns_.  It doesn't do anything with observed data.  So that phrase "that same observed data doesn't show up as a validation error" doesn't really make sense.  I don't think the validator is intended to "pre-check" observed data against a pattern to determine whether an attempted pattern match would cause an error.

But if I am misunderstanding, a concrete example would help!

**Comment by rpatterson** [comment]
The issue I'm describing isn't that the pattern is invalid, but that the observed data is invalid.  I only mention running the pattern matcher to demonstrate that the values I'm talking about are invalid.  So I'll start over and try to state it more simply.

If a STIX observed data's `objects` property contains an `artifact` object with a `payload_bin` property, [it's contents should be base64 encoded](https://docs.google.com/document/d/1b7ZahfoxIepkv3MoaxGvA4WUq6GaCl5S_VPKpIEEAm4/edit#heading=h.4jegwl6ojbes) and so such an observed data artifact should fail validation if the value is not base64 encoded.  Currently such values do not fail validation.  For example...
```
{
  "type": "artifact", 
  "mime_type": "application/octet-stream",
  "payload_bin": "I am not base64 encoded"
}
```

...should fail validation but currently it succeeds.

I stated it more broadly above because [`cti-pattern-matcher` decodes *all* properties whose names end with `_bin` or `_hex`](https://github.com/oasis-open/cti-pattern-matcher/blob/master/stix2matcher/matcher.py#L280).  So on that count it seems like either `cti-pattern-matcher` should be more explicit in which properties it decodes, or the this validator should be more broad in which properties it requires to be encoded.

**Comment by gtback** [comment]
Oh, I misread the original comment. I assumed it was the *pattern* with unencoded data that was causing an error, not the observed-data. Sorry

**Comment by gtback** [comment]
@rpatterson: your comment above was *seconds* before my comment where I realized my mistake (so now I feel extra bad about it!). It does make sense for the `cti-stix-validator` to check that the values of any property ending in `_bin` is valid Base64 data. I think @clenk is already working on fixing this (despite me sending everyone down the wrong trail with my first comment).

**Comment by clenk** [comment]
The JSON schemas used by the STIX validator were not correctly checking for Base64 encoded strings, but I have submitted a fix. Thank you for finding the bug!

**Comment by gtback** [comment]
Thanks, @clenk. I'm going to leave this open until we incorporate the schema changes into the validator.
