### ISSUE TITLE
Is it possible to validate the 'manifest' objects using stix2validator

### ISSUE THREAD

**Issue by basicdock** [oasis-open/cti-stix-validator#170]
Hi.
I get manifest using taxii2client lib:
{
	'objects': [{
			'id': 'indicator--uuid,
			'date_added': '2021-04-28T00:00:00Z',
			'version': '2021-04-28T00:00:00Z',
			'media_type': 'application/stix+json;version=2.1'
		}
	],
	'more': True,
	'next': 'key'
}

stix2validator needs type:
    if 'type' not in instance:
        raise ValidationError("Input must be an object with a 'type' property.")

In specification for 2.0 and 2.1 manifest responce - objects array.
https://docs.oasis-open.org/cti/taxii/v2.1/cs01/taxii-v2.1-cs01.pdf

Is it possible to validate the 'manifest' objects using stix2validator

**Comment by clenk** [comment]
Hi @basicdock, this validator is only focused on the STIX 2 format and the Manifest is a structure from the TAXII standard. Thus it is currently out of scope for this library.

**Comment by basicdock** [comment]
Thanks.
