### ISSUE TITLE
Add or modify option to allow providing a single schema instead of directory

### ISSUE THREAD

**Issue by clenk** [oasis-open/cti-stix-validator#171]
suggested by @rpiazza

**Comment by rpiazza** [comment]
actually, this isn't exactly what I was suggesting.  You might have a lot of extensions - so it would look like this:

stix2_validator --additional-schema-dir /path/to/my/extension-schemas <stix_file.json>

**Comment by clenk** [comment]
There was a misunderstanding of the issue. Also, the `--schemas` option already does this.
