### ISSUE TITLE
UUIDv5 validation

### ISSUE THREAD

**Issue by Swisskill** [oasis-open/cti-stix-validator#193]
The validator does not seem to correctly determine if something is a UUIDv5. If a SCO is not in v5, it gives a warning. However if it is, it does not recognize relationships to the SCO as a valid [object]--[UUID]

For example:
[X] relationship--dcc7e8e6-2109-452c-a871-80fe1ac7eec8: target_ref: 'file--deee0715-1a53-5caa-8151-f81d6a5ab723' does not match the id format ([object-type]--[UUID])

**Comment by clenk** [comment]
@Swisskill Which version of the validator are you using? I do not get this error on the most recent version.

**Comment by Swisskill** [comment]
I apologize for the very late reply. I believe for one reason or another that the problem is resolved
