### ISSUE TITLE
Add option to silence all output written to stdout

### ISSUE THREAD

**Issue by StephenThomson** [oasis-open/cti-stix-validator#20]
Would be nice if all output to stdout could be silenced.

**Comment by gtback** [comment]
Hi, @StephenThomson. Is this still an issue? Just wanted to make sure you didn't close this by accident.

**Comment by StephenThomson** [comment]
Hi Greg,

Yes this is still an issue but I closed it because I forked to fix it myself and didn't want you to waste effort.

Steve

**Comment by gtback** [comment]
Ok, thanks! I'm going to reopen this so I don't forget about it, but since you've made a comment, we'll remember that you're working on it. 

If you haven't already, you'll need to sign a [CLA](https://www.oasis-open.org/resources/open-repositories/cla) before we can merge any of your changes in.

**Comment by gtback** [comment]
Closed by @StephenThomson in #21
