### ISSUE TITLE
draft7_format_checker is deprecated

### ISSUE THREAD

**Issue by subbyte** [oasis-open/cti-stix-validator#200]
I get a warning about a library update:
```
  /usr/lib64/python3.10/site-packages/stix2validator/validator.py:11: DeprecationWarning: Accessing jsonschema.draft7_format_checker is deprecated and will be removed in a future release. Instead, use the FORMAT_CHECKER attribute on the corresponding Validator.
    from jsonschema import Draft7Validator, RefResolver, draft7_format_checker
```
[The function](https://github.com/oasis-open/cti-stix-validator/blob/4c6650f29b69082817955b653622f540f080339f/stix2validator/validator.py#L534) may need an update to avoid breaking down in future release.

**Comment by clenk** [comment]
This would be fixed by https://github.com/oasis-open/cti-stix-validator/pull/191, which switches to a more recent draft of JSON Schema.

**Comment by captainGeech42** [comment]
Now that #191 is merged, would it be possible to publish a new release to pypi?

**Comment by ejratl** [comment]
@captainGeech42 Yes, give me a few days and I will do that.

**Comment by ejratl** [comment]
@captainGeech42 The new release is on pypi. I'd love it if you would test it to see if it fixes your problem.

**Comment by captainGeech42** [comment]
@ejratl I still see 3.0.2 as the latest on pypi, is there a different package I should be looking at?

![image](https://user-images.githubusercontent.com/4255667/204008470-2f84a791-ee57-4a7b-ba01-57fda0eaa7ce.png)

**Comment by rpiazza** [comment]
Hi @captainGeech42,

Sorry - 3.1.0 was withdrawn, but there should be a new (better) release soon.

**Comment by ejratl** [comment]
@captainGeech42 3.1.2 is up now, please give it a whirl: https://pypi.org/project/stix2-validator/3.1.2/

**Comment by captainGeech42** [comment]
On 3.1.2, I'm getting an exception for the newer format now being deprecated. 

```
$ pip freeze | grep stix2-validator
stix2-validator==3.1.2

$ pip freeze | grep jsonschema
fastjsonschema==2.15.3
jsonschema==4.16.0

$ python script.py 2>&1 | grep stix2      
../../venv/py3/lib/python3.10/site-packages/stix2validator/validator.py:11
../../venv/py3/lib/python3.10/site-packages/stix2validator/validator.py:11
  /home/geech/venv/py3/lib/python3.10/site-packages/stix2validator/validator.py:11: DeprecationWarning: Accessing jsonschema.draft202012_format_checker is deprecated and will be removed in a future release. Instead, use the FORMAT_CHECKER attribute on the corresponding Validator.
```

**Comment by captainGeech42** [comment]
@ejratl would it be possible to cut a new release to PyPI with this bug fix in it?

**Comment by ejratl** [comment]
@captainGeech42 Since you are asking for it, yes, I can do that.

**Comment by captainGeech42** [comment]
awesome, thank you very much!

**Comment by ejratl** [comment]
@captainGeech42 please try 3.1.3 and let me know if it works for you

**Comment by captainGeech42** [comment]
looks good now, thank you @ejratl !
