### ISSUE TITLE
3.1.0 missing schemas

### ISSUE THREAD

**Issue by Cisphyx** [oasis-open/cti-stix-validator#205]
It looks like the newly released 3.1.0 is not including any schemas when installing via pip, is that intended or is it a packaging issue?

**Comment by ejratl** [comment]
This is a problem with the release. Working on it now and will retract the release if I don't fix it soon. Sorry for the inconvenience.

**Comment by ejratl** [comment]
I have yanked the release for now. Will re-release when I can embed the schema.

**Comment by Cisphyx** [comment]
Sounds good, thanks!
