### ISSUE TITLE
HTTPSConnectionPool Fatal Error

### ISSUE THREAD

**Issue by henrawrrr** [oasis-open/cti-stix-validator#215]
While trying to run the given code: 
`from stix2validator import validate_file, print_results

results = validate_file("test.json")
print_results(results)`

It throws "Fatal Error: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /oasis-open/cti-stix2-json-schemas/stix2.1/schemas/common/identifier.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)')))"

The test JSON is just an object copied from https://oasis-open.github.io/cti-documentation/examples/identifying-a-threat-actor-profile

**Comment by rpiazza** [comment]
This is a ssl certificate issue unrelated to the validator.  Check to see if your certificates are set up correctly.
