### ISSUE TITLE
Proposal: Remove requests / requests cache / appdirs

### ISSUE THREAD

**Issue by vEpiphyte** [oasis-open/cti-stix-validator#221]
Hello,

I think it it would be really great if this library could remove the `requests`, `requests-cache` and `appdirs` dependencies in it. The behavior of pulling down data in the the enums.py files ( see https://github.com/oasis-open/cti-stix-validator/blob/master/stix2validator/v21/enums.py#L2195 ) can lead to inputs which have differing validation statuses based on the operational environment in which this library code is executed in.

While pulling down and caching the IETF data locally is nice, this data could easily be added as package data, just like the schema .json files are packaged. This would remove an entire dependency chain from the library that isn't strictly necessary, while making the validation process more consistent across environments.

If a PR was put up for making this change, would it be considered?

**Comment by rpiazza** [comment]
@clink - this seems somewhat reasonable, but is this handled by the no-cache command line arg?  If that is for something else, I can see a new arg to avoid the requests - but then what would be used to check for valid values?

**Comment by clenk** [comment]
This makes sense to me; I can't speak for the current maintainers but I would be favorable to seeing such a PR. Would just need to think about how to update the included data (the schemas are git submodules, but these types of data wouldn't be). Also this change would probably warrant a major version bump.

**Comment by vEpiphyte** [comment]
@rpiazza  @clenk I put up a PR to show how this can be done inline.

Current PR removes the caching options, which would be a backwards incompatible change and require a major version release.
