### ISSUE TITLE
Cut new release 3.2.0

### ISSUE THREAD

**Issue by ostefano** [oasis-open/cti-stix-validator#232]
Since https://github.com/oasis-open/cti-stix-validator/pull/228 is now merged, we should cut a new release.

CC @adulau @clenk @rpiazza @ejratl

**Comment by ostefano** [comment]
Blocked by https://github.com/oasis-open/cti-stix-validator/pull/235

**Comment by ostefano** [comment]
Now unblocked.

**Comment by rpiazza** [comment]
Release done on 4/5 by @rpiazza and @clenk
