### ISSUE TITLE
Seeing error w/ indicator w/ a pattern

### ISSUE THREAD

**Issue by jmgnc** [oasis-open/cti-stix-validator#29]
With the attached file, I see:
[X] Fatal Error: expected string or buffer

It appears that it is trying to parse/understand the pattern, but it fails.
[test.txt](https://github.com/oasis-open/cti-stix-validator/files/1154374/test.txt)

This is at 63a339b75caf65b7ec4e13d13f073f5b4a29b60b.

A previous version of the validator was known to work properly on a similar indicator w/ a pattern.  I don't remember what version that was.

**Comment by clenk** [comment]
Thank you @jmgnc! This is a bug introduced by changes in the pattern validator, specifically [this commit](https://github.com/oasis-open/cti-pattern-validator/commit/f2fb1c3c02b58ac94a24191a95a15027e9dc1a88). A fix is in the works.
