### ISSUE TITLE
stix validator does not handle list of stix objects in a file

### ISSUE THREAD

**Issue by jmgnc** [oasis-open/cti-stix-validator#31]
If you attempt to validate a file which contains a list of stix objects (for testing w/ the stix pattern matcher code), you cannot, and will get the error:
[X] Fatal Error: Input must be an object with a 'type' property.

Please support files w/ a list of stix objects, validating each object in the list.

Thanks.

**Comment by clenk** [comment]
Thank you, @jmgnc, this is a good idea. Unfortunately I don't have the cycles to devote to this right now, but we would welcome a Pull Request with this functionality!

**Comment by gtback** [comment]
@clenk , we can close this, correct?

**Comment by clenk** [comment]
Yes, this was fixed in #36 thanks to @chisholm.
