### ISSUE TITLE
Support additional schemas (custom extensions)

### ISSUE THREAD

**Issue by clenk** [oasis-open/cti-stix-validator#43]
We should add an option to allow custom additional schemas. The validator should then ensure the STIX input validates against both the official specification (via the [OASIS schemas](https://github.com/oasis-open/cti-stix2-json-schemas)) and these additional schemas.

**Comment by gtback** [comment]
Without getting too fancy, we may want to ensure we handle both expansion (custom extension) and restriction (think profiles). If it's easier to do this separately, we can create separate issues.
