### ISSUE TITLE
Validate has unhandled exception with bad patterns

### ISSUE THREAD

**Issue by infosec-alchemist** [oasis-open/cti-stix-validator#44]
Rather than returning the appropriate error message, there is an unhandled exception.

Using Python3.

Tested with "validate-pattern" and sending in "file:size = 1280"

**Comment by infosec-alchemist** [comment]
I wasn't haven't this problem before.  This might be something I did.  Closing for now.

**Comment by gtback** [comment]
Thanks, @infosec-alchemist . We'll look into this.

**Comment by clenk** [comment]
Hi @infosec-alchemist! This appears to be an issue for the *pattern* validator, not the *stix* validator. I was unable to generate an unhandled exception with that input and replicate your issue. If this is still a problem, would you mind creating a [new issue on the _pattern_ validator repo](https://github.com/oasis-open/cti-pattern-validator/issues/new) and including some more info on the specific exception being thrown and a stack trace?

Thanks!
