### ISSUE TITLE
This pattern is failing to be validated

### ISSUE THREAD

**Issue by infosec-alchemist** [oasis-open/cti-stix-validator#45]
This STIX pattern fails validation.

[emailaddr:value MATCHES '.+\\@ibm\\.com$' OR file:name MATCHES '^Final Report.+\\.exe$']

Error message is

FAIL: Error found at line 1:25. mismatched input ''' expecting StringLiteral

**Comment by clenk** [comment]
Hi, @infosec-alchemist! The [STIX 2.0 Patterning Spec](http://docs.oasis-open.org/cti/stix/v2.0/cs01/part5-stix-patterning/stix-v2.0-cs01-part5-stix-patterning.html#_Toc496717742) specifies that in a string the backslash character must be followed by another backslash or an apostrophe. You'll need to escape your backslashes. The following passes the _pattern_ validator for me:
```
[email-addr:value MATCHES '.+\\@IBM\\.com$' OR file:name MATCHES '^Final Report.+\\.exe$']
```

Note that the pattern will need another layer of escaping for JSON. So in the actual JSON given to the _STIX_ validator, each instance of the backslash from your original pattern would need to be <code>'\\\\\\\\'</code>.

**Comment by clenk** [comment]
I'm going to close this as there hasn't been any updates for a few months. Please feel free to reopen it or file a new issue if the above suggestion did not work for you. Thanks!
