### ISSUE TITLE
warn instead of error for SHOULD

### ISSUE THREAD

**Issue by jmgnc** [oasis-open/cti-stix-validator#5]
When providing a custom property, it errors about it (prints in red), instead of warning about it.
[!] course-of-action--d6e1dbd5-104f-4a09-b76c-3531d3398ecb: {103} Custom property 'obs_ref' should have a type that starts with 'x_' followed by a source unique identifier (like a domain name with dots replaced by dashes), a dash and then the name.

**Comment by gtback** [comment]
Thanks, @jmgnc.

Right now we don't distinguish "errors" from "warnings". Specific checks can be turned on and off using `--enable` or `--disable`. Additionally, all of the SHOULD checks can be turned off with `--lax`. 

Do you think the current implementation is sufficient, or do we need to distinguish errors from warnings (besides being able to selectively turn them on and off)?

**Comment by jmgnc** [comment]
I think supporting warnings would be a good thing.  It lets those warnings
be annoying as opposed to turning them off prevents you from seeing when
new warning happen.  It's also not clear from the table which of the errors
are SHOULDs versus MUSTs.

**Comment by d-hostetler** [comment]
It'd be great to see this same warning behavior applied to open vocabularies. According to the spec, it's acceptable to use custom values in an `open-vocab` field (which consumers are free to ignore).
> The value of the property **SHOULD** be chosen from the suggested vocabulary but **MAY** be any other string value. 

The validator treats this as an error right now.

Example:
```
malware--031e8443-3a44-5068-b897-7a242b69b0b6: {216} labels contains a value not in the malware-label-ov vocabulary.
```

**Comment by gtback** [comment]
Sounds good! We'll take a look.
