### ISSUE TITLE
relationships & sighting objects

### ISSUE THREAD

**Issue by tlhampton13** [oasis-open/cti-stix-validator#68]
The following STIX 2 bundle currently passes validation.  Is the "sighting-of" relationship between a Sighting and Malware objects valid?  Seems the validator currently does not enforce the relationships between the SDOs.  Will this be enforced in the future?

```json
{
  "type": "bundle",
  "spec_version": "2.0",
  "id": "bundle--8f361d59-3d22-47c4-bab1-67560aecb34a",
  "objects": [
    {
      "type": "sighting",
      "sighting_of_ref": "malware--cad074cf-d120-456a-98b5-236d4e3aa025",
      "count": 0,
      "summary": false,
      "id": "sighting--1232725b-6211-4c91-bc71-c9159bd487b1",
    },
    {
      "type": "relationship",
      "target_ref": "malware--cad074cf-d120-456a-98b5-236d4e3aa025",
      "source_ref": "sighting--1232725b-6211-4c91-bc71-c9159bd487b1",
      "id": "relationship--5b6c5dc9-5d0b-4f0b-be23-626531b250f3",
      "relationship_type": "sighting-of",
      "created": "2018-07-11T11:17:48-04:00",
      "modified": "2018-07-11T11:17:48-04:00",
    },
    {
      "type": "malware",
      "name": "malware--cad074cf",
      "labels": ["ransomware"],
      "description": "",
      "id": "malware--cad074cf-d120-456a-98b5-236d4e3aa025"
    }
  ]
}
```

**Comment by gtback** [comment]
Thanks, @tlhampton13 ! I thought there was a statement in the spec that SROs could never be the source_ref or target_ref in a relationship; I know that was the intent. The only things I can find in the spec right now only seem to suggest rather than require that. 

This is certainly something we need to address, either (most likely) as an error or (possibly) as a warning.

**Comment by tlhampton13** [comment]
Thanks, @gtback

I know this comment is not applicable to the validator and that the STIX 2 spec is already published, but I would prefer the Sighting object to be an SDO instead of an SRO.  Connected to the other SDOs by "sighting-of", "where-sighted", and "observed" relationships. That's what some of our folks are trying to do with the above.  It would make some things easier.  Oh well, can't change the spec.

Given that the validator may enforce we'll avoid creating relationships to SROs.

**Comment by ikiril01** [comment]
I think the language is fairly clear in the definition of the Relationship SRO that it can only reference SDOs. If you look at the definition of `source_ref`/`target_ref`: 

"The id of the source (from) object. The value MUST be an ID reference to an SDO (i.e., it cannot point to an SRO, Bundle, or Marking Definition)."

**Comment by tlhampton13** [comment]
@ikiril01 Thank you for pointing out the specific language in the Spec.

**Comment by gtback** [comment]
Thanks @ikiril01 , that's exactly what I was looking for!

**Comment by longdhnguyen** [comment]
This bundle also passed the validator, and I do not think it should: 
```
{
  "type": "bundle",
  "id": "bundle--44af6c39-c09b-49c5-9de2-394224b04982",
  "spec_version": "2.0",
  "objects": [
    {
      "type": "indicator",
      "id": "indicator--a932fcc6-e032-176c-126f-cb970a5a1ade",
      "created": "2014-02-20T09:16:08.989Z",
      "modified": "2014-02-20T09:16:08.989Z",
      "name": "File hash for Poison Ivy variant",
      "description": "This file hash indicates that a sample of Poison Ivy is present.",
      "labels": [
        "malicious-activity"
      ],
      "pattern": "[file:hashes.'SHA-256' = 'ef537f25c895bfa782526529a9b63d97aa631564d5d789c2b765448c8635fb6c']",
      "valid_from": "2014-02-20T09:00:00.000000Z"
    },
    {
      "type": "malware",
      "id": "malware--fdd60b30-b67c-11e3-b0b9-f01faf20d111",
      "created": "2014-02-20T09:16:08.989Z",
      "modified": "2014-02-20T09:16:08.989Z",
      "name": "Poison Ivy",
      "labels": [
        "remote-access-trojan"
      ]
    },
    {
      "type": "relationship",
      "id": "relationship--f191e70e-1736-47c3-b0f9-fdfe01387eb1",
      "created": "2014-02-20T09:16:08.989Z",
      "modified": "2014-02-20T09:16:08.989Z",
      "relationship_type": "indicates",
      "source_ref": "indicator--b932fcc6-e032-176c-126f-cb970a5a1ade",
      "target_ref": "malware--fdd60b30-b67c-11e3-b0b9-f01faf20d111"
    }
  ]
```

Note that I modified the uuid of the indicator object in source_ref of the SRO. I think we also want to make sure the SDO ids in the SRO are valid.

**Comment by gtback** [comment]
I would say that's a separate issue, @tlhampton13 (enforcing that all referenced objects are contained within the same bundle). There's nothing in the STIX spec that prohibits STIX objects from referencing objects not included in the same bundle. There may be some restrictions in the interoperability specification, in which case I can imagine adding a mode to the validator to check that, but I wouldn't make it the default.

**Comment by tlhampton13** [comment]
@gtback are you responding to @longdhnguyen comment or the original issue?

**Comment by gtback** [comment]
Sorry, that was for @longdhnguyen . I edited the above issue. Thanks for pointing that out.

**Comment by longdhnguyen** [comment]
I have created a new issue #72 for the comment above. Thanks @gtback

**Comment by clenk** [comment]
The validator currently enforces this. The above stix content should result in the following error:

```
    [X] relationship--5b6c5dc9-5d0b-4f0b-be23-626531b250f3: source_ref: Relationships cannot link bundles, marking definitions, sightings, or other relationships. This field must contain the id of an SDO.
```

I'm closing this, but if you are still facing this issue @tlhampton13 feel free to reopen!
