### ISSUE TITLE
error on -ov values

### ISSUE THREAD

**Issue by jmgnc** [oasis-open/cti-stix-validator#7]
The pattern matcher presents an error when a value is used that is NOT in an -ov.  An -ov is an open vocab and is allowed to have ANY value, and so the validator MUST NOT show it as an error, as it is valid and well formed to have non vocab value:
[!] indicator--38f66507-4e25-4cd1-8a43-52bd45e18c37: {214} labels contains a value not in the indicator-label-ov vocabulary.

**Comment by gtback** [comment]
Our intention was to promote the use of the the vocab values to improve interoperability. Even though we say "SHOULD be chosen from the suggested vocabulary" in the spec, this is perhaps different from other "SHOULD" requirements. This check can be selectively disabled; do you think we should do something different?

**Comment by jmgnc** [comment]
--lax should be documented in the README.  and IMO be made the default.  It's also not clear which checks that --lax disables, and the table doesn't tell you which ones are disabled.

I think I suggested this in another issue is that SHOULD's should be marked as warnings (yellow), but NOT fail the tests even in the default (non --lax) case.

If the defaults are stricter than the spec, this needs to be very clear in the README (IMO, it's not), and made more clear in the error messages.

**Comment by gtback** [comment]
Agreed we need to better document the options, and make more clear what the defaults are.
