### ISSUE TITLE
External References whose source_name includes 'capec' are invalid

### ISSUE THREAD

**Issue by rpiazza** [oasis-open/cti-stix-validator#71]
The following should be valid STIX.  Notice that the source_name includes the string 'capec', but that should be legal

```
       {
            "source_name": "reference_from_capec",
            "description": "The Official Social Engineering Portal, Social-Engineer.org, Tick Tock Computers, LLC",
            "url": "http://www.social-engineer.org",
            "external_id": "REF-348"
        }
```

Here is the error message:

[X] attack-pattern--0a19a0a2-1b7b-4dde-99b9-624edc549928: external_references[0]: If the external reference is a CVE, 'source_name' must be 'cve' and 'external_id' must be in the CVE format (CVE-YYYY-NNNN+). If the external reference is a CAPEC, 'source_name' must be 'capec' and 'external_id' must be in the CAPEC format (CAPEC-N+). If the external reference is neither, it must contain the 'source_name' property and at least one of the 'external_id', 'url', or 'description' properties.

Changing the source_name to ```reference_from_CAPEC``` avoids this issue.

**Comment by zrush-mitre** [comment]
I believe this error is fixed and this issue can be closed @clenk
