### ISSUE TITLE
Enforce referenced objects in relationship objects

### ISSUE THREAD

**Issue by longdhnguyen** [oasis-open/cti-stix-validator#72]
This bundle also passed the validator, and I do not think it should:

```
{
  "type": "bundle",
  "id": "bundle--44af6c39-c09b-49c5-9de2-394224b04982",
  "spec_version": "2.0",
  "objects": [
    {
      "type": "indicator",
      "id": "indicator--a932fcc6-e032-176c-126f-cb970a5a1ade",
      "created": "2014-02-20T09:16:08.989Z",
      "modified": "2014-02-20T09:16:08.989Z",
      "name": "File hash for Poison Ivy variant",
      "description": "This file hash indicates that a sample of Poison Ivy is present.",
      "labels": [
        "malicious-activity"
      ],
      "pattern": "[file:hashes.'SHA-256' = 'ef537f25c895bfa782526529a9b63d97aa631564d5d789c2b765448c8635fb6c']",
      "valid_from": "2014-02-20T09:00:00.000000Z"
    },
    {
      "type": "malware",
      "id": "malware--fdd60b30-b67c-11e3-b0b9-f01faf20d111",
      "created": "2014-02-20T09:16:08.989Z",
      "modified": "2014-02-20T09:16:08.989Z",
      "name": "Poison Ivy",
      "labels": [
        "remote-access-trojan"
      ]
    },
    {
      "type": "relationship",
      "id": "relationship--f191e70e-1736-47c3-b0f9-fdfe01387eb1",
      "created": "2014-02-20T09:16:08.989Z",
      "modified": "2014-02-20T09:16:08.989Z",
      "relationship_type": "indicates",
      "source_ref": "indicator--b932fcc6-e032-176c-126f-cb970a5a1ade",
      "target_ref": "malware--fdd60b30-b67c-11e3-b0b9-f01faf20d111"
    }
  ]
```
Note that I modified the uuid of the indicator object in source_ref of the SRO. I think we also want to make sure all of the SDO ids in every SROs are valid.

**Comment by clenk** [comment]
Hi @longdhnguyen, thanks for the feedback! So you want to verify that the SDOs being referenced by the SRO are contained within the same bundle? I believe the STIX 2.0 specification allows referencing objects that are not distributed within the same bundle. The indicator with an id starting with 'b' could be a valid object that just isn't included in the bundle.

**Comment by longdhnguyen** [comment]
Hello @clenk, yes that is what I'd like to have as an option or to have the script raising a warning for this. 

Also, I have found the exact part where you said "I believe the STIX 2.0 specification allows referencing objects that are not distributed within the same bundle":

**STIX™ Version 2.0. Part 1: STIX Core Concepts section ​3.2​ IDs and References**:

> ID references can refer to objects to which the consumer/producer may not currently have. This specification does not address the implementation of ID reference resolution.

This was sneaky since I expect this information is covered in the Relationship section :)
