### ISSUE TITLE
1.1.1 on PyPI is missing schemas directory

### ISSUE THREAD

**Issue by rooterkyberian** [oasis-open/cti-stix-validator#83]
With `stix2-validator==1.1.1`
Every attempt at validation fails with `result.errors` containing following `SchemaError`: `Cannot locate a schema for the object's type, nor the base schema (core.json).`

work fine with `stix2-validator==1.1.0`

**Comment by clenk** [comment]
@rooterkyberian Thanks for creating an issue. Can you try with the just-released `stix2-validator==1.1.2` and see if that fixed it for you?

**Comment by rooterkyberian** [comment]
@clenk yes it does, thank you!
