### ISSUE TITLE
Malformed hash values are not caught by the validator

### ISSUE THREAD

**Issue by rpiazza** [oasis-open/cti-stix-validator#85]
It appears that the grammar would need to be changed.  Not sure it is worth it.

**Comment by rpiazza** [comment]
It was in a pattern created by the elevator.  The validator doesn't flag it as being malformed (it doesn't have 64 characters).

file:hashes.'SHA-256' = 'AA76D3AF03B44639148D190785EAB9720471FFC28C71468182B786ED0B0EB'

I can't attach a json file??????

I made it a TXT file
[stix-9281.json.txt](https://github.com/oasis-open/cti-stix-validator/files/2718726/stix-9281.json.txt)

**Comment by clenk** [comment]
Since this is a problem with the pattern validator, I made an issue there: https://github.com/oasis-open/cti-pattern-validator/issues/59

Thanks for bringing this up!
