### ISSUE TITLE
why didn't check 'name' property in process? (OBSERVABLE_PROPERTIES)

### ISSUE THREAD

**Issue by hswlow** [oasis-open/cti-stix-validator#86]
https://github.com/oasis-open/cti-stix-validator/blob/ed380c18f6c4aa0f56eb6acc6bae8327419fc73b/stix2validator/v21/enums.py#L852

The validator which version is '2.0' have checked name property in OBSERVABLE_PROPERTIES 'process'.
But the validator which version is '2.1' didn't check this. The 'name' property is missed in 'v21/enums.py' file.
Is it intended? or bug?

**Comment by hswlow** [comment]
> [cti-stix-validator/stix2validator/v21/enums.py](https://github.com/oasis-open/cti-stix-validator/blob/ed380c18f6c4aa0f56eb6acc6bae8327419fc73b/stix2validator/v21/enums.py#L852)
> 
> Line 852 in [ed380c1](/oasis-open/cti-stix-validator/commit/ed380c18f6c4aa0f56eb6acc6bae8327419fc73b)
> 
>  'process': [ 
> The validator which version is '2.0' have checked name property in OBSERVABLE_PROPERTIES 'process'.
> But the validator which version is '2.1' didn't check this. The 'name' property is missed in 'v21/enums.py' file.
> Is it intended? or bug?

sorry. This is noted in STIX2 documentation which version is 1.1.1.
I'll close this issue.
thanks.

**Comment by clenk** [comment]
Hi, @hswlow. Yes, in STIX 2.1 the `name` property on Process has been removed because it is duplicative with the `image_ref.name` property.
