### ISSUE TITLE
when spec_version is 2.0 on bundle, do not warn

### ISSUE THREAD

**Issue by jmgnc** [oasis-open/cti-stix-validator#88]
On a stix bundle that has a spec_version of 2.0, the latest version of the validator returns a warning:
    [!] Warning: bundle--59afb48d-0f9c-434d-be6a-69515424b0c3: {101} Custom property 'spec_version' should have a type that starts with 'x_' followed by a source unique identifier (like a domain name with dots replaced by hyphen), a hyphen and then the name.

It should NOT return a warning, as that is properly formatted STIX 2.0.

This was found when checking against https://github.com/pan-unit42/playbook_viewer/blob/master/playbook_json/darkhydrus.json

**Comment by clenk** [comment]
Thanks for the issue; yes, this is an oversight. Code on the current master branch only checks the `--version` option but we need to update it to also check `spec_version` in bundles.
